# Generated by Django 2.0.7 on 2018-07-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, unique=True, verbose_name='机柜位置')),
                ('server_type', models.CharField(max_length=200, verbose_name='设备型号')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('changed_time', models.DateTimeField(auto_now=True)),
                ('sn', models.CharField(max_length=200, verbose_name='序列号')),
                ('ip_address', models.CharField(max_length=200, unique=True, verbose_name='IP地址')),
                ('user_name', models.CharField(max_length=200, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('mgmt_ip', models.CharField(max_length=200, verbose_name='管理IP')),
                ('mgmt_user', models.CharField(max_length=200, verbose_name='管理用户名')),
                ('mgmt_pass', models.CharField(max_length=200, verbose_name='管理密码')),
                ('apps', models.CharField(max_length=200, verbose_name='项目名')),
                ('order', models.CharField(blank=True, max_length=200, verbose_name='负责人')),
                ('op', models.CharField(max_length=200, verbose_name='维护人')),
                ('host_name', models.CharField(blank=True, max_length=20, verbose_name='主机名')),
                ('ma_info', models.CharField(blank=True, max_length=20, verbose_name='过保日期')),
            ],
            options={
                'verbose_name': '物理机管理',
                'get_latest_by': 'changed_time',
            },
        ),
    ]
