# Generated by Django 2.0.7 on 2018-07-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwdmanger', '0002_auto_20180708_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwd_info',
            name='ip_address',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
