# Generated by Django 2.0.7 on 2018-07-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwdmanger', '0003_auto_20180709_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwd_info',
            name='apps',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwd_info',
            name='cluster_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwd_info',
            name='order',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwd_info',
            name='user_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
