# Generated by Django 2.0.7 on 2018-07-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwdmanger', '0004_auto_20180711_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwd_info',
            name='host_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
