# Generated by Django 2.0.7 on 2018-07-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwdmanger', '0005_passwd_info_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwd_info',
            name='op',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
