# Generated by Django 2.0.7 on 2018-07-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwdmanger', '0006_passwd_info_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwd_info',
            name='order',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
