# Generated by Django 2.0.7 on 2018-07-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwdmanger', '0007_auto_20180711_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwd_info',
            options={'get_latest_by': 'changed_time', 'verbose_name': '虚拟机密码表'},
        ),
        migrations.AlterField(
            model_name='passwd_info',
            name='apps',
            field=models.CharField(max_length=200, verbose_name='应用名'),
        ),
        migrations.AlterField(
            model_name='passwd_info',
            name='cluster_name',
            field=models.CharField(max_length=200, verbose_name='集群名'),
        ),
        migrations.AlterField(
            model_name='passwd_info',
            name='host_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='passwd_info',
            name='ip_address',
            field=models.CharField(max_length=200, unique=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='passwd_info',
            name='op',
            field=models.CharField(max_length=200, verbose_name='维护人'),
        ),
        migrations.AlterField(
            model_name='passwd_info',
            name='order',
            field=models.CharField(blank=True, max_length=200, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='passwd_info',
            name='os_type',
            field=models.CharField(max_length=200, verbose_name='系统类型'),
        ),
        migrations.AlterField(
            model_name='passwd_info',
            name='password',
            field=models.CharField(max_length=200, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='passwd_info',
            name='user_name',
            field=models.CharField(max_length=200, verbose_name='用户名'),
        ),
    ]
